name: Main Workflow

on: [push, pull_request]

jobs:
  run:
    name: Run

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node: [21, 22]

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}

      - name: Setup pnpm
        run: npm install pnpm -g

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm test
